schema_version: 1
funding: external-aid-program
contract_nature: services
sort: publication-number DESC
scope: ACTIVE
only_latest_versions: false
pursuable_form_types:
  - result
  - competition
  - planning
page_size: 250
